/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2021-02-15 11:23:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._0205;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import kr.or.ddit.prod.vo.ProdVO;

public final class prod_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<ProdVO> prod = (List<ProdVO>) request.getAttribute("123456");

      out.write("\r\n");
      out.write("\r\n");
      out.write("[\r\n");

	int i = prod.size();
	for (ProdVO pr : prod) {
		i--;

      out.write("\r\n");
      out.write("\r\n");
      out.write("{ \r\n");
      out.write("\"id\" : \"");
      out.print( pr.getProd_id() );
      out.write("\",\r\n");
      out.write("\"name\" : \"");
      out.print( pr.getProd_name() );
      out.write("\",\r\n");
      out.write("\"lgu\" : \"");
      out.print( pr.getProd_lgu() );
      out.write("\",\r\n");
      out.write("\"buyer\" : \"");
      out.print( pr.getProd_buyer() );
      out.write("\",\r\n");
      out.write("\"cost\" : \"");
      out.print( pr.getProd_cost() );
      out.write("\",\r\n");
      out.write("\"price\" : \"");
      out.print( pr.getProd_price() );
      out.write("\",\r\n");
      out.write("\"sale\" : \"");
      out.print( pr.getProd_sale() );
      out.write("\",\r\n");
      out.write("\"outline\" : \"");
      out.print( pr.getProd_outline() );
      out.write("\",\r\n");
      out.write("\"detail\" : \"");
      out.print( pr.getProd_detail() );
      out.write("\",\r\n");
      out.write("\"img\" : \"");
      out.print( pr.getProd_img() );
      out.write("\",\r\n");
      out.write("\"totalstock\" : \"");
      out.print( pr.getProd_totalstock() );
      out.write("\",\r\n");
      out.write("\"insdate\" : \"");
      out.print( pr.getProd_insdate() );
      out.write("\",\r\n");
      out.write("\"properstock\" : \"");
      out.print( pr.getProd_properstock() );
      out.write("\",\r\n");
      out.write("\"size\" : \"");
      out.print( pr.getProd_size() );
      out.write("\",\r\n");
      out.write("\"color\" : \"");
      out.print( pr.getProd_color() );
      out.write("\",\r\n");
      out.write("\"delivery\" : \"");
      out.print( pr.getProd_delivery() );
      out.write("\",\r\n");
      out.write("\"unit\" : \"");
      out.print( pr.getProd_unit() );
      out.write("\",\r\n");
      out.write("\"qtyin\" : \"");
      out.print( pr.getProd_qtyin() );
      out.write("\",\r\n");
      out.write("\"qtysale\" : \"");
      out.print( pr.getProd_qtysale() );
      out.write("\"\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("     }\r\n");

	if (i > 0)
			out.print(",");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("]\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
